name: Auto-Assign and Add Issues to N-Zik Roadmap Backlog

on:
  issues:
    types: [opened]

permissions:
  issues: write
  checks: write

jobs:
  assign_and_add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to actor and add to project backlog
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectId = "YOUR_PROJECT_ID";
            const statusFieldId = "YOUR_STATUS_FIELD_ID";
            const backlogOptionId = "YOUR_BACKLOG_OPTION_ID";

            const contentId = context.payload.issue.node_id;
            const issueNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const assignee = context.actor;

            // Add issue to project
            const addItemResponse = await github.graphql(`
              mutation ($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId,
              contentId
            });

            const itemId = addItemResponse.addProjectV2ItemById.item.id;
            console.log("Added issue to project, itemId:", itemId);

            // Assign issue to the actor
            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: issueNumber,
              assignees: [assignee]
            });
            console.log(`Assigned issue #${issueNumber} to ${assignee}`);

            // Set Status field to Backlog
            await github.graphql(`
              mutation ($itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: { singleSelectOptionId: $optionId }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              itemId,
              fieldId: statusFieldId,
              optionId: backlogOptionId
            });
            console.log("Set project item status to Backlog");
