name: Comment or close on label

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: ${{ github.repository }}
  NUMBER: "${{ github.event.pull_request.number || github.event.issue.number }}"

jobs:
  # Explicitly for issue either opened after the commits were made
  # but before the release. Or when it's not closed by mention in
  # commit message.
  patched:
    if: github.event.label.name == 'patched'
    
    runs-on: ubuntu-latest
    
    permissions:
      # Allows GITHUB_TOKEN to modify issue tickets
      issues: write
      
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          BODY: >
            This issue has been patched in recent commits. Please wait for the next release.

            > Please DO NOT close this issue manually. It will be handled automatically once the new release is published.

  # Handle PR that contains already implemented code
  pr-implemented:
    if: github.event.label.name == 'implemented' && github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    
    permissions:
      # Allows GITHUB_TOKEN to modify pull requests
      pull-requests: write  
      
    steps:
      - name: Add comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          BODY: >
            This feature already exists in the codebase.

            > This pull request will be closed. If you have any further questions, feel free to comment below.

      - name: Close pull request
        run: gh pr close "$NUMBER"

  # Handle implemented features that are submitted as issues
  issue-implemented:
    if: github.event.label.name == 'implemented' && github.event_name == 'issues'
    
    runs-on: ubuntu-latest
    
    permissions:
      issues: write  
      
    steps:
      - name: Add comment
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          BODY: >
            This feature already exists in the codebase.

            > This ticket will be closed. If you have any further questions, feel free to comment below.

      - name: Close issue
        run: gh issue close "$NUMBER"
  
  # Borked PR is when it causes compile failures or unexpected behavior
  borked:
    if: github.event.label.name == 'borked'
    
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write      
      
    steps:
      - name: Close pull request
        run: gh pr close "$NUMBER"
