name: Sync labels

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          source-repo: knighthat/Kreate  # owner/repo format, not full URL
          delete-other-labels: false     # keep existing labels that aren't in source
          token: ${{ secrets.GITHUB_TOKEN }}
